apiVersion: v1
kind: Secret
metadata:
  name: notification-secret
stringData:
  GMAIL_ADDRESS: "nwadialongozi@gmail.com" #enter your email to get the id
  GMAIL_PASSWORD: "syst wpom mrhm cnwn" #generate one-time password from your google account
type: Opaque

# Passw0rd@1234